platform :ios, '15.1'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

# Uncomment to use dynamic frameworks (required for some libraries)
# use_frameworks! :linkage => :static

target 'OrbitPay' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes engine (recommended for production)
    :hermes_enabled => true,
    :fabric_enabled => false,
    # App flip utility
    :flipper_configuration => FlipperConfiguration.disabled,
    # App store compliance
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Navigation
  pod 'RNScreens',    :path => '../node_modules/react-native-screens'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNSafeAreaContext', :path => '../node_modules/react-native-safe-area-context'

  # Security
  pod 'RNKeychain',   :path => '../node_modules/react-native-keychain'
  pod 'RNBiometrics', :path => '../node_modules/react-native-biometrics'

  # UI
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons',    :path => '../node_modules/react-native-vector-icons'

  # Camera/Images
  pod 'RNImagePickerManager', :path => '../node_modules/react-native-image-picker'

  # Reanimated
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # SVG
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # AsyncStorage
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  # Clipboard
  pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'

  # Post-install hooks
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['ENABLE_BITCODE']             = 'NO'
      end
    end
  end
end
